stopAllRunningBuild: true

# Node config
# "standalone", "k8s"
nodeType: "standalone"
nodeName: ""
podTemplate: ""
workspaceVolumePath: "/tmp/jenkins"
keepBuilderPod: false
activeDeadlineSeconds: 1800

# "GIT_DESCRIBE", "GIT_FILE", "JENKINS_BUILD_NUMBER"
versionMethod: "GIT_DESCRIBE"
# The git root path if versionMethod="GIT_DESCRIBE"
# The relative path of the directory in the workspace
versionRootPath: "."
# The file contains version data if versionMethod="GIT_FILE"
versionFile: "_version.txt"

# Notification common config
notifications: []
notificationFailureOnly: false
notificationSendFailureToStd: true
# Email config
notificationEmailStdReceiverVar: "IDO_NOTIFICATION_EMAIL"
notificationEmailFailureReceiverVar: "IDO_NOTIFICATION_FAILURE_EMAIL"
notificationEmailStdReceiver: ""
notificationEmailFailureReceiver: ""
# Slack config
notificationSlackStdReceiverVar: "IDO_NOTIFICATION_SLACK"
notificationSlackFailureReceiverVar: "IDO_NOTIFICATION_FAILURE_SLACK"
notificationSlackStdReceiver: ""
notificationSlackFailureReceiver: ""
# Dingtalk config
notificationDingtalkStdReceiverVar: "IDO_NOTIFICATION_DINGTALK"
notificationDingtalkFailureReceiverVar: "IDO_NOTIFICATION_FAILURE_DINGTALK"
notificationDingtalkStdReceiver: ""
notificationDingtalkFailureReceiver: ""

# Source code root path. A relative path to workspace root folder
srcRootPath: "."

# Java common config
# "maven", "gradle"
javaBuildTool: "maven"
# JDK version of build tool, can be "8", "11", "17", "19"
jdkVersion: "8"
mavenVersion: "3.8.6"
gradleVersion: "7.6"
javaModuleName: "."
javaUpdateDependencies: true

# Docker image config
imageName: ""
registryPull:
  url: ""
  credentialsId: ""
registryPush:
  url: "registry.cn-zhangjiakou.aliyuncs.com/bizconf_devops"
  credentialsId: "registry"

# SpringBoot config
springBoot:
  mainClass: ""
  appRoot: "/app"
  baseImage: "amazoncorretto:8"
  jvmFlages: "-Duser.timezone=PRC -Dfile.encoding=UTF-8"
  environment: "TZ='Asia/Shanghai'"