stopAllRunningBuild: true

# Node config
# "standalone", "k8s"
nodeType: "standalone"
nodeName: ""
podTemplate: ""
workspaceVolumePath: "/tmp/jenkins"

# "GIT_DESCRIBE", "GIT_FILE", "JENKINS_BUILD_NUMBER"
versionMethod: "GIT_DESCRIBE"
# The git root path if versionMethod="GIT_DESCRIBE"
# The relative path of the directory in the workspace
versionRootPath: "."
# The file contains version data if versionMethod="GIT_FILE"
versionFile: "_version.txt"

# Notification common config
notifications: []
notificationFailureOnly: false
notificationSendFailureToStd: true
# Email config
notificationEmailStdReceiverVar: "IDO_NOTIFICATION_EMAIL"
notificationEmailFailureReceiverVar: "IDO_NOTIFICATION_FAILURE_EMAIL"
notificationEmailStdReceiver: ""
notificationEmailFailureReceiver: ""
# Slack config
notificationSlackStdReceiverVar: "IDO_NOTIFICATION_SLACK"
notificationSlackFailureReceiverVar: "IDO_NOTIFICATION_FAILURE_SLACK"
notificationSlackStdReceiver: ""
notificationSlackFailureReceiver: ""
# Dingtalk config
notificationDingtalkStdReceiverVar: "IDO_NOTIFICATION_DINGTALK"
notificationDingtalkFailureReceiverVar: "IDO_NOTIFICATION_FAILURE_DINGTALK"
notificationDingtalkStdReceiver: ""
notificationDingtalkFailureReceiver: ""

# Source code root path. A relative path to workspace root folder
srcRootPath: "."

# Java common config
# "maven", "gradle"
buildTool: "maven"
useWrapper: true