# Use mirror to pull builder images
imagePullMirror: true

# Builder image pull secret
# kubectl create secret docker-registry builder-pull-secret --docker-server=<你的镜像仓库服务器> --docker-username=<你的用户名> --docker-password=<你的密码>
imagePullSecret: "builder-pull-secret"

# Image format: "oci", "docker"
imageFormat: "docker"

# The type of volume to use for the workspace of builder pod
workspaceVolume:
  # hostPath, nfs, pvc
  type: "pvc"
  hostPath: ""
  nfsServerAddress: ""
  nfsServerPath: ""
  pvcName: "jenkins-agent-data"

# Android command line tools download url
androidCmdLineToolsUrl: "https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip"

# CocoaPods repo url, e.g.: https://github.com/CocoaPods/Specs.git
cocoapodsRepoUrl: "https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git"

# Keep the builder pod in minutes maximally
keepBuilderPodMaxMinutes: 1440