# Builder image pull secret
# kubectl create secret docker-registry builder-pull-secret --docker-server=<你的镜像仓库服务器> --docker-username=<你的用户名> --docker-password=<你的密码>
imagePullSecret: "builder-pull-secret"

# The type of volume to use for the workspace of builder pod
workspaceVolume:
  # hostPath, nfs, pvc
  type: "pvc"
  hostPath: ""
  nfsServerAddress: ""
  nfsServerPath: ""
  pvcName: "jenkins-test-agent-data"