# Use mirror to pull builder images
imagePullMirror: true
imageMirrors:
  "cr.l5d.io": "l5d.m.daocloud.io"
  "docker.elastic.co": "elastic.m.daocloud.io"
  "docker.io": "docker.m.daocloud.io"
  "gcr.io": "gcr.m.daocloud.io"
  "ghcr.io": "ghcr.m.daocloud.io"
  "k8s.gcr.io": "k8s-gcr.m.daocloud.io"
  "registry.k8s.io": "k8s.m.daocloud.io"
  "mcr.microsoft.com": "mcr.m.daocloud.io"
  "nvcr.io": "nvcr.m.daocloud.io"
  "quay.io": "quay.m.daocloud.io"
  "registry.jujucharms.com": "jujucharms.m.daocloud.io"
  "rocks.canonical.com": "rocks-canonical.m.daocloud.io"

# Builder image pull secret
# kubectl create secret docker-registry builder-pull-secret --docker-server=<你的镜像仓库服务器> --docker-username=<你的用户名> --docker-password=<你的密码> -n <namespace>
imagePullSecret: "builder-pull-secret"

# Image format: "oci", "docker"
imageFormat: "docker"

# The type of volume to use for the workspace of builder pod
workspaceVolume:
  # hostPath, nfs, pvc
  type: "pvc"
  hostPath: ""
  nfsServerAddress: ""
  nfsServerPath: ""
  pvcName: "jenkins-agent-data"

showRawYaml: false

inboundAgentImage: "docker.io/xinnj/inbound-agent:4.13.3-1-alpine-jdk11-nolog"

# Android command line tools download url
androidCmdLineToolsUrl: "https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip"

# CocoaPods repo url, e.g.: https://github.com/CocoaPods/Specs.git
cocoapodsRepoUrl: "https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git"

# Keep the builder pod in minutes maximally
keepBuilderPodMaxMinutes: 1440

dotnetSdkPath: "R:/dotnet"
nugetSource: "https://nuget.cdn.azure.cn/v3/index.json"

smbServer:
  internal: "samba-server"
  external: "${IDO_CLUSTER_HOSTNAME}:${IDO_SMB_NODE_PORT}"
  shareName: "data"
  user: "uploader"
  password: "PleaseUploadHere"

macos:
  builderImage: "nexus-docker-5000:5000/docker-osx-slim:1.0.0"
  remoteBuilderImage: "docker.io/xinnj/ssh-client:1.0.0"

win:
  builderImage: "nexus-docker-5000:5000/docker-win-vm:1.0.0"
  remoteBuilderImage: "docker.io/xinnj/ssh-client:1.0.0"
