# The type of volume to use for the workspace of builder pod
workspaceVolume:
  # hostPath, nfs, pvc
  type: "pvc"
  hostPath: ""
  nfsServerAddress: ""
  nfsServerPath: ""
  pvcName: "jenkins-test-workspace-data"