# The type of volume to use for the workspace of builder pod
workspaceVolume:
  # hostPath, nfs, pvc
  type: "hostPath"
  hostPath: "/tmp/jenkins"
  nfsServerAddress: ""
  nfsServerPath: ""
  pvcName: ""