## Common process config
productName: ""

# Stop all running build of the same job
stopSameJob: true
# Stop all running build of the invoked job
stopInvokedJob: true

# Do UT and Code Analysis in parallel
parallelUtAnalysis: false

# Do Build and Archive in parallel
parallelBuildArchive: false

# Log more information
debug: false

# Source code root path. A relative path to workspace root folder
srcRootPath: "."

# Trigger by upstream projects
dependOn: []
#dependOn:
#  - name: ""
#    branch: ""

# Downstream projects to be invoked
jobsInvoked: []
#jobsInvoked:
#  - name: ""
#    branch: ""

# Customer build scripts
customerBuildScript:
  afterScm: "ido-cluster/after-scm"
  afterVersioning: "ido-cluster/after-versioning"
  beforeBuild: "ido-cluster/before-build"
  build: "ido-cluster/build"
  afterBuild: "ido-cluster/after-build"
  afterArchive: "ido-cluster/after-archive"

## Node config
nodeName: ""
podTemplate: ""
keepBuilderPodMinutes: 0

## Version config
# "GIT_DESCRIBE", "GIT_FILE", "JENKINS_BUILD_NUMBER"
versionMethod: "GIT_DESCRIBE"
# The git root path if versionMethod="GIT_DESCRIBE"
# The relative path of the directory in the workspace
versionRootPath: "."
# The file contains version data if versionMethod="GIT_FILE"
versionFile: "_version.txt"
# Specify the version of the build
version: ""

## Notification config
notification:
  # Notification type: "email", "slack", "dingtalk", "wecom"
  type: [ ]
  # Only notify failure result
  failureOnly: false
  # Send failure message to failure & success receivers
  sendFailureToSuccess: true
  # Email config
  email:
    # Folder property name, which value is a comma separated list of email recipients
    successReceiverFolderProperty: "IDO_NOTIFICATION_EMAIL"
    failureReceiverFolderProperty: "IDO_NOTIFICATION_FAILURE_EMAIL"
    # comma separated list of email recipients
    successReceiver: ""
    failureReceiver: ""
  # Slack config
  slack:
    successReceiverFolderProperty: "IDO_NOTIFICATION_SLACK"
    failureReceiverFolderProperty: "IDO_NOTIFICATION_FAILURE_SLACK"
    successReceiver: ""
    failureReceiver: ""
  # Dingtalk config
  dingtalk:
    successReceiverFolderProperty: "IDO_NOTIFICATION_DINGTALK"
    failureReceiverFolderProperty: "IDO_NOTIFICATION_FAILURE_DINGTALK"
    successReceiver: ""
    failureReceiver: ""
  # Wecom config
  wecom:
    successReceiverFolderProperty: "IDO_NOTIFICATION_WECOM"
    failureReceiverFolderProperty: "IDO_NOTIFICATION_FAILURE_WECOM"
    successReceiver: ""
    failureReceiver: ""

## Java common config
java:
  # "maven", "gradle"
  buildTool: "maven"
  # Builder image with JDK installed
  builderImage: "docker.io/eclipse-temurin:11-jdk"
  mavenVersion: "3.8.6"
  defaultMavenSettings: "builder/default-maven-settings.xml"
  gradleVersion: "7.6"
  defaultGradleInitScript: "builder/default-gradle-init.gradle"
  moduleName: "."
  forceUpdateDependencies: false

## Docker image config
# Dockerfile used to build image
dockerFile: ""
# Pull registry info
registryPull:
  url: "docker.io"
  credentialsId: ""
# Push registry info
registryPush:
  url: "nexus-docker-5001:5001"
  credentialsId: "uploader"

## Helm chart config
helm:
  buildChart: true
  chartPath: "helm"
  repo: "http://nexus:8081/nexus/repository/helm-hosted/"
  uploadCredentialId: "uploader"
  chartVersion: ""
  deploy:
    # dev, qa, prod
    env: ""
    # Credential of kubeconfig file
    kubeconfigCredentialId: ""
    # Credential of AWS if the cluster is EKS
    aws:
      accessKeyCredentialId: ""
      region: "cn-north-1"
    # Secret used to pull images
    imagePullSecret:
      name: "image-pull"
      registry: ""
      # Credential of username/password to login registry
      credentialId: "registry"
    namespace: "default"
    releases: []
    #  - name: ""
        # Helm chart name. Same as 'name' if empty.
    #    chart: ""
        # Helm chart value file.
        # For dev env, the default is the value file inside chart.
        # For qa & prod env, the default is "<chart>/values-<env>.yaml".
    #    valueFile: ""
    #    valueSet: "key1=val1,key2=val2"

## File server config
fileServer:
  uploadUrl: "${IDO_FILE_UPLOAD_URL}"
  downloadUrl: "${IDO_FILE_DOWNLOAD_URL}"
  # must end with '/'
  uploadRootPath: "/"

## SpringBoot config
springBoot:
  mainClass: ""
  appRoot: "/app"
  baseImage: "docker.io/eclipse-temurin:11-jre"
  jvmFlages: "-Dfile.encoding=UTF-8"
  environment: ""
  # Directories used to add arbitrary files to the image
  extraDirectories: []
  # extraDirectories:
  #   paths:
  #       # The source directory, relative to the project root.
  #     - from:
  #       # The absolute unix path on the container to copy the extra directory contents into.
  #       into:
  # Execute UT
  utEnabled: false
  lineCoverageThreshold: 0
  # execute code analysis
  codeAnalysisEnabled: false
  sonarqubeServerName: ""
  qualityGateEnabled: false
  sonarqubeTimeoutMinutes: 10

## NPM config
npm:
  builderImage: "docker.io/node:20.13.1-slim"
  defaultNpmrc: "builder/default-npmrc"

## Node.js config
nodejs:
  # Same as npm.builderImage if empty
  baseImage: ""
  StartCmd: "npm start"
  # Execute UT (Jest only)
  utEnabled: false
  lineCoverageThreshold: 0
  # Execute code analysis
  codeAnalysisEnabled: false
  sonarqubeServerName: ""
  qualityGateEnabled: false
  sonarqubeTimeoutMinutes: 10

## Node.js config
vue:
  # Must be nginx
  baseImage: "docker.io/nginx:stable"
  # Nginx config file to be copied to runtime container. A relative path to "srcRootPath" property.
  # Empty to use default config
  nginxConfigFile: ""
  # Execute UT (Vitest only)
  utEnabled: false
  lineCoverageThreshold: 0
  # Execute code analysis
  codeAnalysisEnabled: false
  sonarqubeServerName: ""
  qualityGateEnabled: false
  sonarqubeTimeoutMinutes: 10

## Android app config
android:
  sdkPackagesRequired: []
  buildDebug: false
  buildRelease: true
  # Execute UT
  utEnabled: false
  lineCoverageThreshold: 0
  # execute code analysis
  codeAnalysisEnabled: false
  sonarqubeServerName: ""
  qualityGateEnabled: false
  sonarqubeTimeoutMinutes: 10

## Macos builder config
macos:
  # Credential ID of login account of builder machine
  loginCredentialId: "macos-builder-login"
  useCocoapods: false

## Xcode config
xcode:
  path: "/Applications/Xcode.app"
  # Apple connect API key, used by automatic code sign
  authenticationKey:
    IssuerID: ""
    ID: ""
    # Secret file credential
    keyFileCredentialId: "apple-auth-key"

## iOS app config
ios:
  # Credential IDs of code sign certificate if code sign style is Manual
  # The certificate file (p12 format) need be imported into Jenkins as certificate credential
  # certificateCredentialIds:
  #   - "apple_development"
  #   - "apple_distribution"
  certificateCredentialIds: []
  # certCredentialIds: "apple_distribution"
  # Profiles to be imported if code sign style is Manual
  # profiles:
  #   - "<mobileprovision file, relative path to srcRootPath>"
  profiles: []
  # Workspace or project to be built, relative path to srcRootPath
  buildFile: ""
  # Export archive types
  # buildOptions:
  #   - name: "adhoc"
  #     scheme: "<scheme name>"
  #     configuration: "<Debug or Release>"
  #     signStyle: "<Automatic or Manual>"
  #     xcconfig: "<path to xcconfig file, relative path to srcRootPath>"
  #     exportOptionsPlist: "<path to exportOptionsPlist file, relative path to srcRootPath>"
  #   - name: "appstore"
  #     scheme: "<scheme name>"
  #     configuration: "<Debug or Release>"
  #     signStyle: "<Automatic or Manual>"
  #     xcconfig: "<path to xcconfig file, relative path to srcRootPath>"
  #     exportOptionsPlist: "<path to exportOptionsPlist file, relative path to srcRootPath>"
  buildOptions: []
  downloadDisplayImages:
    standard: "${IDO_FILE_DOWNLOAD_URL}/ios-install-images/Install.png"
    fullSize: "${IDO_FILE_DOWNLOAD_URL}/ios-install-images/Install-large.png"
  # Execute UT
  ut:
    enabled: false
    scheme: "Test"
    # Automatic or Manual
    signStyle: "Automatic"
    # Path to xcconfig file, relative path to srcRootPath
    xcconfig: ""
    # Code coverage is not supported yet
    lineCoverageThreshold: 0
  # execute code analysis
  codeAnalysisEnabled: false
  sonarqubeServerName: ""
  qualityGateEnabled: false
  sonarqubeTimeoutMinutes: 10

## dotnet app config
dotnet:
  sdkVersion: ""
  # Workloads to be installed by dotnet command
  workloads: []
  # Solution or project to be built, relative path to srcRootPath
  buildFile: ""
  # Debug or Release
  configuration: "Debug"
  # Publishes the application for a given runtime. See https://learn.microsoft.com/en-us/dotnet/core/rid-catalog
  runtime: ""
  # Wix Cover config file path
  msiConfig: ""
  # Execute UT
  ut:
    enabled: false
    # Test project path, relative path to srcRootPath
    project: ""
    lineCoverageThreshold: 0
  # execute code analysis
  codeAnalysisEnabled: false
  sonarqubeServerName: ""
  qualityGateEnabled: false
  sonarqubeTimeoutMinutes: 10

## Visual Studio config
vs:
  # Path of vcvarsallFile.bat file
  vcvarsallFile: ""
  # The tools architecture to use.
  # x86 | amd64 | x86_amd64 | x86_arm | x86_arm64 | amd64_x86 | amd64_arm | amd64_arm64
  arch: ""

## QT app config
qt:
  QT5_DIR: ""
  qmakeParameters: ""
  # Wix Cover config file path
  msiConfig: ""
## Generic SDK config
sdk:
  autoUpdateSdkInfo: true
  sdkBranch: ""
  sdkInfoFile: ""
  buildDebug: false
