apiVersion: v1
kind: Pod
spec:
  containers:
    - name: helm
      image: "docker.io/xinnj/k8s-tools:1.0.1"
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - <keepBuilderPodMaxMinutes>m
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: workspace-volume
      env:
        - name: "XDG_CONFIG_HOME"
          value: "/tmp"
        - name: "XDG_CACHE_HOME"
          value: "/tmp"
        - name: "XDG_DATA_HOME"
          value: "/tmp"
    - name: jnlp
      image: "<inboundAgentImage>"
      env:
        - name: "JENKINS_AGENT_CACHEDIR"
          value: "/home/jenkins/agent/remoting/jarCache"
  imagePullSecrets:
  - name: <imagePullSecret>
  securityContext:
    runAsGroup: 1000
    runAsUser: 1000
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: vm-agent
                operator: NotIn
                values:
                  - 'True'
