apiVersion: v1
kind: Pod
spec:
  containers:
    - name: builder
      image: amazoncorretto:<jdk-version>
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - <keepBuilderPodMinutes>m
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: workspace-volume
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
      env:
        - name: "XDG_CONFIG_HOME"
          value: "/home/jenkins/agent/jib"
        - name: "MAVEN_USER_HOME"
          value: "/home/jenkins/agent/m2"
        - name: "GRADLE_USER_HOME"
          value: "/home/jenkins/agent/gradle"
    - name: jnlp
      image: "jenkins/inbound-agent:4.11-1-jdk11"
  securityContext:
    runAsGroup: 1000
    runAsUser: 1000