apiVersion: v1
kind: Pod
spec:
  containers:
    - name: builder
      image: <builderImage>
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - <keepBuilderPodMaxMinutes>m
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: workspace-volume
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
      env:
        - name: "XDG_CONFIG_HOME"
          value: "/home/jenkins/agent/jib"
        - name: "MAVEN_USER_HOME"
          value: "/home/jenkins/agent/m2"
        - name: "GRADLE_USER_HOME"
          value: "/home/jenkins/agent/gradle"
        - name: "SONAR_USER_HOME"
          value: "/home/jenkins/agent/sonar"
    - name: helm
      image: "docker.io/xinnj/helm"
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - <keepBuilderPodMaxMinutes>m
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: workspace-volume
    - name: jnlp
      image: "<inboundAgentImage>"
      env:
        - name: "JENKINS_AGENT_CACHEDIR"
          value: "/home/jenkins/agent/remoting/jarCache"
  imagePullSecrets:
  - name: <imagePullSecret>
  securityContext:
    runAsGroup: 1000
    runAsUser: 1000
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: vm-agent
                operator: NotIn
                values:
                  - 'True'
