apiVersion: v1
kind: Pod
spec:
  containers:
    - name: maven
      image: maven:3.8.1-jdk-8
      imagePullPolicy: IfNotPresent
      command:
      - sleep
      args:
      - 99d
      volumeMounts:
      - mountPath: /root/.m2/repository
        name: maven-repo
      - mountPath: /home/jenkins/agent
        name: workspace-volume
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    - name: jnlp
      image: "jenkins/inbound-agent:4.11-1-jdk11"
  securityContext:
    runAsGroup: 1000
    runAsUser: 1000
  volumes:
    - name: maven-repo
      hostPath:
        path: /tmp/maven-repo
        type: "DirectoryOrCreate"