apiVersion: v1
kind: Pod
spec:
  containers:
    - name: sonar-scanner
      image: "docker.io/sonarsource/sonar-scanner-cli"
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - <keepBuilderPodMaxMinutes>m
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: workspace-volume
      env:
        - name: SONAR_USER_HOME
          value: /home/jenkins/agent/sonar
    - name: builder
      image: <builderImage>
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - <keepBuilderPodMaxMinutes>m
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: workspace-volume
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
      env:
        - name: "npm_config_cache"
          value: "/home/jenkins/agent/npm"
    - name: buildah
      image: "quay.io/buildah/stable"
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - <keepBuilderPodMaxMinutes>m
      volumeMounts:
        - mountPath: /var/buildah-cache
          name: buildah-cache
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        privileged: true
    - name: helm
      image: "docker.io/xinnj/helm"
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - <keepBuilderPodMaxMinutes>m
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: workspace-volume
    - name: jnlp
      image: "docker.io/xinnj/inbound-agent:4.11-1-alpine-jdk11-nolog"
      env:
        - name: "JENKINS_AGENT_CACHEDIR"
          value: "/home/jenkins/agent/remoting/jarCache"
  imagePullSecrets:
    - name: <imagePullSecret>
  securityContext:
    runAsGroup: 1000
    runAsUser: 1000
  volumes:
    - name: buildah-cache
      hostPath:
        path: "/home/iDO-Cluster/buildah-cache"
        type: DirectoryOrCreate
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: vm-agent
                operator: DoesNotExist
